language: java
dist: xenial
services:
  - xvfb
jdk:
  - openjdk11
before_script:
  - Xvfb :99 &>/dev/null &
  - export DISPLAY=:99
  - sleep 5
script:
  - mvn clean
  - mvn verify coveralls:report
  - mvn compile javafx:jlink
